apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice-deployment
  labels:
    app: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - name: orderservice
          image: adeeshsharma/orderservice
          ports:
            - containerPort: 5001
