apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  selector:
    app: orderservice
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 5001
      nodePort: 31112
